- src/ibmiotf/api.py
Please review and accept the pull request for the updated ReST Api calls.
> Update ReST APIs

- README.md
Does this module work with Python 2.7.9 or only with Python3?  A bit more clarity on this question in the Readme would be useful.
I hereby accept the [CLA](https://github.com/ibm-messaging/iot-python/blob/master/CLA.md).
> Bumped the version of Python 3.4.2 to 3.4.3

- docs/Gateway.rst
- docs/GatewayManagement.rst
> added gateway docs

- samples/managedDevice/README.md
raspbian setup link is missing from readme
> Add raspbian setup to managedDevice sample readme

- docs/python_cli_for_manageddevice.rst
- samples/managedDevice/dmeAction.py
- src/ibmiotf/device.py
- test/deviceTest.py
Changes include
- Support of list of bundleIds for DME Actions in device.py
- Added unit tests for DME with bundleIds in deviceTest.py
- Updated documentation for DME with bundleIds
- Updated sample - dmeAction.py with sample implementation of DME Action for publish event interval.
> Merge bundleIds support for DME

- test/deviceTest.py
Changes contain update to device unit tests to match with latest publishEvent changes for HTTP.
> Updated device unit tests to comply with publishEvent using HTTP

- src/ibmiotf/__init__.py
- src/ibmiotf/application.py
- src/ibmiotf/device.py
- src/ibmiotf/gateway.py
> fix race causing deadlock with on_publish callbacks

- samples/gatewayExamples/gatewayPublishEvent.py
myData will now have values instead of text, iotp display will have datapoints corresponding with values instead of no datapoint and a json value allowing these fields to be utilized on the dashboard
> altered myData variable

- src/ibmiotf/gateway.py
Adds a new class to handle Watson notifications as the regular expression used to match the message is different from that used to match a command.
> Handle gateway notifications

- src/ibmiotf/__init__.py
- src/ibmiotf/gateway.py
Added more detailed error messages.
> Added comments and extra error messages

- src/ibmiotf/gateway.py
Adds a 'on_disconnect' method to match 'on_connect'.  Allows a subclass of Client to override and react to a disconnect event.
> Clear connectEvent when disconnected

- src/ibmiotf/device.py
- Fixed issue with missing logging argument;
- optimize similar double encoding;
- Threads with function names;
- PEP8 formatting;
> Some fixes, optimizations, usability changes and pep8 style

- README.md
- setup.py
Add Python 3.7 to the lower left corner of https://pypi.org/project/ibmiotf
> Add Pypy trove classifier for Python 3.7

- samples/psutil/README.md
- samples/psutil/src/iotpsutil.py
> Add disk utilization

- test/test_application_messages.py
- test/test_gateway_messages.py
> Add test coverage to gateway and app messages

- src/wiotp/sdk/api/state/schemas.py
- test/test_api_state_schemas.py
> Creating/Updating Schema can now accept dictionaries - no need for user invoked json.dumps

- test/test_state_utils.py
Handled Exception in Testcleanup() to fix travis build
> Resolving current travis failings jonah

- .gitignore
- src/wiotp/sdk/api/state/__init__.py
- src/wiotp/sdk/api/state/thingState.py
- src/wiotp/sdk/api/state/thingTypes.py
- src/wiotp/sdk/api/state/things.py
- test/test_api_state_thingState.py
- test/test_api_state_thing_types.py
- test/test_api_state_things.py
- test/test_state_utils.py
Re-uploaded due to naming issues
> Addthingsupportdean

- samples/psutil/src/iotpsutil.py
Correct the callback function to parse commandId
Check that the interval is an integer
> Fix command callback function

- samples/dataManagement/cleanUp/controlledResourceCleanUp.py
- samples/dataManagement/cleanUp/fullResourceCleanUp.py
- samples/dataManagement/cleanUp/resourceFetch.py
- src/wiotp/sdk/application/config.py
3 new samples in the clean up folder under data management.
1. Full clean up (deletes every resource in the org)
2. Controlled clean up (explicitly define resources to delete)
3. Sample to collect all resources to input into samples easier
> Clean up samples

- samples/simpleDevice/simpleDevice.py
import was using the old ibmiotf library. 
Also default org of quickstart doesn't support device auth
> Fix up simpleDevice sample

- samples/simpleApp/simpleApp.py
- SImple app was using ibmiotf - updated to wiotp.sdk
> Updated Simpleapplication

- samples/simpleDevice/README.md
- src/wiotp/sdk/client.py
/samples/simpleDevice/README.md:
- Removed references to ibmiotf
- Updated example config file to match the format used across the rest of the configuration files in the SDK.
/src/wiotp/sdk/client.py:
- minor wording correction
> Simple device documentation jonah

- .travis.yml
- README.md
- setup.py
- test/testUtils/__init__.py
- tox.ini
👋 Python 2.7, you had a good run!
> Remove Python 2.7 (and 3.5) support

- src/wiotp/sdk/api/registry/devices.py
- src/wiotp/sdk/api/registry/types.py
- src/wiotp/sdk/api/state/devices.py
Moving total_rows from Device to Devices.
> Total_rows Fix

- test/test_codecs_raw.py
Added invalid encode and decode tests to test_codecs_raw
> Added sdk/messages.py tests

- test/test_api_state_logical_interfaces.py
> Added 3 different tests logical interfaces

- src/wiotp/sdk/api/services/credentials.py
- test/test_api_dsc_cloudant.py
- test/test_api_dsc_db2.py
- test/test_api_dsc_eventstreams.py
- test/test_api_dsc_postgres.py
Added testing for:
- Cloudant
- EventStreams
- DB2
- Postgres
Fixed a typo on line 62 on services/credentials.py
> Unitesting for Cloudant, DB2, Eventstreams, Postgres
